ignore-patterns:
  - (^|/)\..+
  - build/
  - tests/internal
  - tests/external

strictness: veryhigh
autodetect: true
doc-warnings: true
test-warnings: true
member-warnings: false

pep8:
  full: true
  options:
    max-line-length: 79
    single-line-if-stmt: n

pyroma:
  run: true
  disable:
    - PYR15

pep257:
  disable:
    - D105
    - D203
    - D105
