language: python
python:
- '2.7'
install:
- pip install pep8
- pip install pyflakes
- pip install pylint
- pip install coveralls
- pip install future
before_script:
- ./tests.sh
script:
- coverage run dependenpy/tests.py
- coverage report -m
after_success: coveralls
notifications:
  slack:
    secure: hD2sRUSn91cA4qIL1gKQHHCr3wTdzEr4TcFbgQOaIuuEwvwwT0N34gSfntKyQ98D9OKLxFi4sH3ANSM/eH2xka+c5cMb6isdwDborf1s3AB+nI4+zBh1QAjlAOd2qg8YfXbRgRrF6oYN5N3rXFjtHBUQAwf+i/0a6jeLaLAiMaI=
